# Generated by Django 5.1.1 on 2024-10-20 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productlineattribute',
            old_name='attribute_value',
            new_name='value',
        ),
    ]
